# Fuzzy matching stations from 2022 without information

In exploring the issues with inconsistency in station names and station identification both across time and between the ride data and station information data, I determined that 2022 ride data matched the station information data best - unsurprisingly, as the latter dates from early 2023.

Some stations in the ride data did not match both name and station ID with the station information data, but this was typically down to differences in station name (spelling, punctuation, address vs. descriptive name). The location information associated with the ID was generally correct in these situations, meaning they can be used for spatial analysis.

Some station IDs in the ride data, however, did not appear in the station information dataset. This may be because the same station existed in 2023 but the ID had been changed, or because the station location and associated ID no longer existed in 2023.

### Load in packages and data

In [2]:
setwd("../")

In [3]:
library(tidyverse)
library(fuzzyjoin)
library(levitate)

Warning message:
“package ‘tidyverse’ was built under R version 4.2.3”
Warning message:
“package ‘ggplot2’ was built under R version 4.2.3”
Warning message:
“package ‘tibble’ was built under R version 4.2.3”
Warning message:
“package ‘tidyr’ was built under R version 4.2.3”
Warning message:
“package ‘readr’ was built under R version 4.2.3”
Warning message:
“package ‘purrr’ was built under R version 4.2.3”
Warning message:
“package ‘dplyr’ was built under R version 4.2.3”
Warning message:
“package ‘stringr’ was built under R version 4.2.3”
Warning message:
“package ‘forcats’ was built under R version 4.2.3”
Warning message:
“package ‘lubridate’ was built under R version 4.2.3”
── Attaching core tidyverse packages ────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────

In [4]:
data_all_years <- read_csv("./Data/data_all_years.csv")

Rows: 16961551 Columns: 10
── Column specification ──────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): Start.Station.Name, End.Station.Name, User.Type
dbl  (5): Trip.Id, Trip.Duration, Start.Station.Id, End.Station.Id, Bike.Id
dttm (2): Start.Time, End.Time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [5]:
stations <- read_csv("./Data/stations/station_information.csv")

Rows: 661 Columns: 17
── Column specification ──────────────────────────────────────────────────────────────────
Delimiter: ","
chr (6): name, physical_configuration, address, obcn, post_code, cross_street
dbl (6): station_id, lat, lon, altitude, capacity, nearby_distance
lgl (5): is_charging_station, rental_methods, groups, _ride_code_support, is...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [6]:
intersections <- read_csv("./Data/centrelines/Centreline Intersection - 4326.csv")

Rows: 48955 Columns: 21
── Column specification ──────────────────────────────────────────────────────────────────
Delimiter: ","
chr   (7): INTERSECTION_DESC, CLASSIFICATION, CLASSIFICATION_DESC, ELEVATION...
dbl  (10): _id, INTERSECTION_ID, ELEVATION_ID, NUMBER_OF_ELEVATIONS, ELEVATI...
lgl   (2): ELEVATION, HEIGHT_RESTRICTION
dttm  (2): DATE_EFFECTIVE, DATE_EXPIRY

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [7]:
spec(intersections)

cols(
  `_id` = col_double(),
  INTERSECTION_ID = col_double(),
  DATE_EFFECTIVE = col_datetime(format = ""),
  DATE_EXPIRY = col_datetime(format = ""),
  ELEVATION_ID = col_double(),
  INTERSECTION_DESC = col_character(),
  CLASSIFICATION = col_character(),
  CLASSIFICATION_DESC = col_character(),
  NUMBER_OF_ELEVATIONS = col_double(),
  ELEVATION_FEATURE_CODE = col_double(),
  ELEVATION_FEATURE_CODE_DESC = col_character(),
  ELEVATION_LEVEL = col_double(),
  ELEVATION = col_logical(),
  ELEVATION_UNIT = col_character(),
  HEIGHT_RESTRICTION = col_logical(),
  HEIGHT_RESTRICTION_UNIT = col_character(),
  STATE = col_double(),
  TRANS_ID_CREATE = col_double(),
  TRANS_ID_EXPIRE = col_double(),
  OBJECTID = col_double(),
  geometry = col_character()
)

In [38]:
head(intersections)

_id INTERSECTION_ID DATE_EFFECTIVE      DATE_EXPIRY         ELEVATION_ID
1 1   13470264        2008-12-12 04:22:46 3000-01-01 05:00:00    13       
2 2   13470193        2008-12-12 04:22:46 3000-01-01 05:00:00  4718       
3 3   13470188        2008-12-12 04:22:46 3000-01-01 05:00:00 32728       
4 4   13470203        2008-12-12 04:22:46 3000-01-01 05:00:00 21669       
5 5   13470228        2008-12-12 04:22:46 3000-01-01 05:00:00 36820       
6 6   13470242        2008-12-12 04:22:46 3000-01-01 05:00:00  2869       
  INTERSECTION_DESC            CLASSIFICATION CLASSIFICATION_DESC             
1 Robindale Ave / Rimilton Ave MNRSL          Minor-Single Level              
2 Bellman Ave / Valermo Dr     MNRSL          Minor-Single Level              
3 Rimilton Ave / Valermo Dr    SEUSL          Pseudo Intersection-Single Level
4 Valermo Dr / Goa Crt         MNRSL          Minor-Single Level              
5 Valermo Dr / Thirtieth St    MNRSL          Minor-Single Level              
6 Valermo Dr / Delta St        MNRSL          Minor-Single Level              
  NUMBER_OF_ELEVATIONS ELEVATION_FEATURE_CODE ⋯ ELEVATION_LEVEL ELEVATION
1 1                    501300                 ⋯ NA              NA       
2 1                    501300                 ⋯ NA              NA       
3 1                    509200                 ⋯ NA              NA       
4 1                    501300                 ⋯ NA              NA       
5 1                    501300                 ⋯ NA              NA       
6 1                    501300                 ⋯ NA              NA       
  ELEVATION_UNIT HEIGHT_RESTRICTION HEIGHT_RESTRICTION_UNIT STATE
1 None           NA                 None                    8    
2 None           NA                 None                    8    
3 None           NA                 None                    8    
4 None           NA                 None                    8    
5 None           NA                 None                    8    
6 None           NA                 None                    8    
  TRANS_ID_CREATE TRANS_ID_EXPIRE OBJECTID
1 2e+05           -1               1      
2 2e+05           -1               4      
3 2e+05           -1               5      
4 2e+05           -1               7      
5 2e+05           -1               9      
6 2e+05           -1              10      
  geometry                                                                      
1 {'type': 'MultiPoint', 'coordinates': [[-79.5310702158097, 43.6072425849711]]}
2 {'type': 'MultiPoint', 'coordinates': [[-79.5313732423075, 43.609600012102]]} 
3 {'type': 'MultiPoint', 'coordinates': [[-79.5301175801351, 43.6098292200395]]}
4 {'type': 'MultiPoint', 'coordinates': [[-79.5331747278101, 43.6091899836547]]}
5 {'type': 'MultiPoint', 'coordinates': [[-79.5355925204638, 43.6086391702897]]}
6 {'type': 'MultiPoint', 'coordinates': [[-79.5380199282464, 43.6081028218457]]}

### Identify station ID/name combinations in ride data only

Using an anti join, station ID/name combinations that appear in the ride data but not the station information data are identified.

In [8]:
station_id_name_notfound <- anti_join(data_all_years,
                                      stations,
                                      by = join_by(Start.Station.Id == station_id,
                                                   Start.Station.Name == name)) %>%
drop_na(Start.Station.Id, Start.Station.Name) %>%
filter(year(Start.Time) == 2022) %>%
distinct(Start.Station.Id) %>%
left_join(data_all_years) %>%
select(Start.Station.Id, Start.Station.Name) %>%
distinct() %>%
left_join(stations, by = join_by(Start.Station.Id == station_id)) %>%
select(Start.Station.Id, Start.Station.Name, name, address)

Joining with `by = join_by(Start.Station.Id)`


These combinations are then split into cases where the ID is found in the station information data and where they are not.

In [9]:
station_id_found <- station_id_name_notfound %>%
filter(Start.Station.Id %in% stations$station_id)

In [9]:
station_id_found

Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid in this locale”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 2 is invalid in this locale

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, clas

Start.Station.Id Start.Station.Name                           
1  7334             Simcoe St / Wellington St North              
2  7171             Ontario Place Blvd / Lake Shore Blvd W (East)
3  7171             Ontario Place Blvd / Lakeshore Blvd W        
4  7171             Ontario Place Blvd / Remembrance Dr          
5  7250             St. George St / Russell St - SMART           
6  7323             457 King St. W. at Spadina                   
7  7389             College Park- Gerrard Entrance               
8  7398             York St / Harbour St                         
9  7398             York St / Lakeshore St W - South             
10 7332             200 Bloor St. E.                             
11 7057             Simcoe St / Wellington St South              
12 7057             Simcoe St / Wellington St W                  
13 7675             NA                                           
14 7675             1525 Dundas St                               
15 7641             Annette St / Dundas W                        
16 7440             Martin Goodman Trail / Ontario Dr            
17 7208             80 Clinton St (North of College) - SMART     
18 7208             80 Clinton St (North of College)             
19 7327             Davenport Rd / Oakwood Rd - SMART            
20 7666             NA                                           
21 7666             Dundas St W / St Helen Ave - SMART           
22 7092             Pape Subway Green P                          
23 7322             King St W / Brant St                         
24 7386             D'Arcy St. /McCaul St. SMART                 
25 7133             Summerhill Station                           
26 7364             Queen St E / Nursewood Rd (Neville Park Loop)
27 7388             Broadview Ave / Danforth Ave                 
28 7468             Front St / Simcoe St                         
29 7361             Hocken Ave./Vaughan Rd.                      
30 7543             Nassau St / Bellevue Ave                     
⋮  ⋮                ⋮                                            
39 7420             Barton St / Howland St - SMART               
40 7680             NA                                           
41 7680             Princes Gate / Nunavut Dr                    
42 7238             Sorauren/Geoffrey (Sorauren Park) - SMART    
43 7600             Russell St / Huron St - SMART                
44 7356             King St E / Ontario St.                      
45 7269             Toronto Eaton Centre (Yonge St)              
46 7231             Wright / Sorauren (Sorauren Park) - SMART    
47 7202             Queen St W / York St (City Hall)             
48 7237             Ward Ave / Wallace Ave                       
49 7636             Bloor St W / Riverside Ave                   
50 7438             High Park Subway - SMART                     
51 7438             High Park Subway                             
52 7241             519 Church St - SMART                        
53 7486             Gerrard St E / Ted Reeve Dr                  
54 7359             Rosedale Park (20 Schofield Ave)             
55 7368             Lisgar St / Dundas St SMART                  
56 7091             Donlands Station                             
57 7637             Judson St / Royal York                       
58 7497             128 Sterling Ave - SMART                     
59 7142             Bridgeman Ave / Bathurst St                  
60 7094             Chester Station (Green P)                    
61 7094             Chester Station                              
62 7070             25 York St – Union Station South             
63 7070             25 York St \x96 Union Station South          
64 7070             25 York St GÇô Union Station South           
65 7070             25 York St G\xc7\xf4 Union Station South     
66 7070             25 York St ? Union Station South             
67 7070             25 York St \023  Union 

A visual inspection reveals that all stations where the ID but not name are found in the station information data appear to correspond to the correct location.

In [10]:
station_id_notfound <- station_id_name_notfound %>%
filter(!(Start.Station.Id %in% stations$station_id))

In [11]:
station_id_notfound

Start.Station.Id Start.Station.Name                            name address
1  7113             Parliament St / Aberdeen Ave                  NA   NA     
2  7282             Adelaide St W / Bay St - SMART                NA   NA     
3  7013             Scott St / The Esplanade                      NA   NA     
4  7011             Wellington St W / Portland St                 NA   NA     
5  7275             Queen St W / James St                         NA   NA     
6  7491             D'Arcy St / Spadina Ave - SMART               NA   NA     
7  7382             Simcoe St / Adelaide St W                     NA   NA     
8  7372             King St W / Portland St                       NA   NA     
9  7372             Adelaide St W / Portland St                   NA   NA     
10 7255             Stewart St / Bathurst St  - SMART             NA   NA     
11 7544             Foster Pl / Elizabeth St - SMART              NA   NA     
12 7544             Foster Pl / Elizabeth St                      NA   NA     
13 7017             Widmer St / Adelaide St W                     NA   NA     
14 7017             Widmer St / Adelaide St                       NA   NA     
15 7293             College St / McCaul St                        NA   NA     
16 7653             Bloor St W / Indian Rd                        NA   NA     
17 7049             Queen St W / Portland St                      NA   NA     
18 7509             Ontario St / King St E                        NA   NA     
19 7167             Queen St E / George St (Moss Park)            NA   NA     
20 7060             Princess St / Adelaide St E                   NA   NA     
21 7060             Princess St / Adelaide St                     NA   NA     
22 7525             Fennings St / Queen St W - SMART              NA   NA     
23 7525             Fennings St / Queen St W                      NA   NA     
24 7426             Fleet St / Garrison Rd (Fort York)            NA   NA     
25 7179             Bloor GO / UP Station (West Toronto Railpath) NA   NA     
26 7179             Bloor GO / UP Station/ Rail Path              NA   NA     
27 7177             East Liberty St / Pirandello St               NA   NA     
28 7578             Oak St / Parliament St                        NA   NA     
29 7472             Dundas St E / Victoria St                     NA   NA     
30 7407             University Ave / Queen St W                   NA   NA     
31 7423             Merton St / Al Green Ln - SMART               NA   NA     
32 7423             Merton St / Al Green Ln                       NA   NA     
33 7535             Wolsley St / Palmerston Ave - SMART           NA   NA     
34 7134             Marlborough Ave / Yonge St                    NA   NA     
35 7019             Temperance St. Station                        NA   NA     
36 7019             Temperance St / Yonge St                      NA   NA     
37 7413             Dundas St W / Watkinson Ave - SMART           NA   NA     
38 7413             Dundas St W / Watkinson Ave                   NA   NA     
39 7560             Glenwood Ave / Runnymede Rd - SMART           NA   NA     
40 7560             Glenwood Ave / Runnymede Rd                   NA   NA     
41 7330             Lee Ave / Queen St E                          NA   NA     
42 7392             Woodbine Subway Green P SMART                 NA   NA     
43 7482             Danforth Ave / Sibley Ave - SMART             NA   NA     
44 7482             Danforth Ave / Sibley Ave                     NA   NA     
45 7621             Long Branch GO Station                        NA   NA     
46 7638             Warehouse EBS-Station                         NA   NA

### Check if stations exist in station information with different ID

To determine if there are station that have apparently been given new IDs between 2022 and April 2023, the best check is to see if any station names for the unknown IDs match names or addresses in the station information data.

In [11]:
station_id_changed <- station_id_notfound %>%
mutate(output = coalesce(stations$station_id[match(Start.Station.Name, stations$name)],
                         stations$station_id[match(Start.Station.Name, stations$address)]))

In [13]:
station_id_changed

Start.Station.Id Start.Station.Name                            name address
1  7113             Parliament St / Aberdeen Ave                  NA   NA     
2  7282             Adelaide St W / Bay St - SMART                NA   NA     
3  7013             Scott St / The Esplanade                      NA   NA     
4  7011             Wellington St W / Portland St                 NA   NA     
5  7275             Queen St W / James St                         NA   NA     
6  7491             D'Arcy St / Spadina Ave - SMART               NA   NA     
7  7382             Simcoe St / Adelaide St W                     NA   NA     
8  7372             King St W / Portland St                       NA   NA     
9  7372             Adelaide St W / Portland St                   NA   NA     
10 7255             Stewart St / Bathurst St  - SMART             NA   NA     
11 7544             Foster Pl / Elizabeth St - SMART              NA   NA     
12 7544             Foster Pl / Elizabeth St                      NA   NA     
13 7017             Widmer St / Adelaide St W                     NA   NA     
14 7017             Widmer St / Adelaide St                       NA   NA     
15 7293             College St / McCaul St                        NA   NA     
16 7653             Bloor St W / Indian Rd                        NA   NA     
17 7049             Queen St W / Portland St                      NA   NA     
18 7509             Ontario St / King St E                        NA   NA     
19 7167             Queen St E / George St (Moss Park)            NA   NA     
20 7060             Princess St / Adelaide St E                   NA   NA     
21 7060             Princess St / Adelaide St                     NA   NA     
22 7525             Fennings St / Queen St W - SMART              NA   NA     
23 7525             Fennings St / Queen St W                      NA   NA     
24 7426             Fleet St / Garrison Rd (Fort York)            NA   NA     
25 7179             Bloor GO / UP Station (West Toronto Railpath) NA   NA     
26 7179             Bloor GO / UP Station/ Rail Path              NA   NA     
27 7177             East Liberty St / Pirandello St               NA   NA     
28 7578             Oak St / Parliament St                        NA   NA     
29 7472             Dundas St E / Victoria St                     NA   NA     
30 7407             University Ave / Queen St W                   NA   NA     
31 7423             Merton St / Al Green Ln - SMART               NA   NA     
32 7423             Merton St / Al Green Ln                       NA   NA     
33 7535             Wolsley St / Palmerston Ave - SMART           NA   NA     
34 7134             Marlborough Ave / Yonge St                    NA   NA     
35 7019             Temperance St. Station                        NA   NA     
36 7019             Temperance St / Yonge St                      NA   NA     
37 7413             Dundas St W / Watkinson Ave - SMART           NA   NA     
38 7413             Dundas St W / Watkinson Ave                   NA   NA     
39 7560             Glenwood Ave / Runnymede Rd - SMART           NA   NA     
40 7560             Glenwood Ave / Runnymede Rd                   NA   NA     
41 7330             Lee Ave / Queen St E                          NA   NA     
42 7392             Woodbine Subway Green P SMART                 NA   NA     
43 7482             Danforth Ave / Sibley Ave - SMART             NA   NA     
44 7482             Danforth Ave / Sibley Ave                     NA   NA     
45 7621             Long Branch GO Station                        NA   NA     
46 7638             Warehouse EBS-Station                         NA   NA     
   output
1    NA  
2    NA  
3    NA  
4    NA  
5    NA  
6    NA  
7    NA  
8  7720  
9    NA  
10   NA  
11   NA  
12   NA  
13   NA  
14   NA  
15   NA  
16   NA  
17   NA  
18   NA  
19   NA  
20   NA  
21   NA  
22   NA  
23   NA  
24   NA  
25   NA  
26   NA  
27   NA  
28   NA  


In [14]:
stations %>% subset(station_id == 7720)

station_id name                    physical_configuration lat     lon      
1 7720       King St W / Portland St SMARTMAPFRAME          43.6444 -79.40065
  altitude address              capacity is_charging_station rental_methods
1 0        620 King Street West 16       FALSE               NA            
  groups obcn nearby_distance _ride_code_support post_code is_valet_station
1 NA     NA   350             TRUE               M5V 1M6   NA              
  cross_street
1 NA

We find that just 1 station obviously exists under a new ID in the station information data. This is 7372, which in 2022 was listed at both Adelaide and Portland and King W and Portland (very close geographically) but in 2023 is at the latter under the ID 7720. We can add 7372 to the station information data using the information from 7720 to approximate its location.

In [12]:
station_7372 <- stations %>% subset(station_id == 7720)
station_7372$station_id <- 7372
stations_update_2022 <- stations %>% add_row(station_7372)
station_id_changed <- station_id_changed %>% filter(Start.Station.Id != 7372)

In [77]:
saveRDS(stations_update_2022, "./Data/stations_update_2022.rds")

While exact matches are rare, some stations have had IDs replaced while the names have changed subtly or are formatted differently in the station information data. To attempt to identify those, a fuzzy-matched join is worth trying.

In [13]:
stations_fuzz_name <- stringdist_join(station_id_changed,
                                      stations,
                                      mode = "left",
                                      by = c(Start.Station.Name = "name"),
                                      max_dist = 6)

In [14]:
stations_fuzz_name %>% select(Start.Station.Id,
                              Start.Station.Name,
                              station_id,
                              name.y,
                              address.y)

Start.Station.Id Start.Station.Name                            station_id
1  7113             Parliament St / Aberdeen Ave                    NA      
2  7282             Adelaide St W / Bay St - SMART                  NA      
3  7013             Scott St / The Esplanade                      7716      
4  7011             Wellington St W / Portland St                 7469      
5  7275             Queen St W / James St                         7542      
6  7275             Queen St W / James St                         7712      
7  7491             D'Arcy St / Spadina Ave - SMART                 NA      
8  7382             Simcoe St / Adelaide St W                       NA      
9  7255             Stewart St / Bathurst St  - SMART               NA      
10 7544             Foster Pl / Elizabeth St - SMART                NA      
11 7544             Foster Pl / Elizabeth St                        NA      
12 7017             Widmer St / Adelaide St W                       NA      
13 7017             Widmer St / Adelaide St                         NA      
14 7293             College St / McCaul St                        7007      
15 7293             College St / McCaul St                        7023      
16 7293             College St / McCaul St                        7078      
17 7293             College St / McCaul St                        7199      
18 7293             College St / McCaul St                        7547      
19 7293             College St / McCaul St                        7762      
20 7653             Bloor St W / Indian Rd                          NA      
21 7049             Queen St W / Portland St                      7542      
22 7049             Queen St W / Portland St                      7720      
23 7509             Ontario St / King St E                        7373      
24 7167             Queen St E / George St (Moss Park)              NA      
25 7060             Princess St / Adelaide St E                     NA      
26 7060             Princess St / Adelaide St                       NA      
27 7525             Fennings St / Queen St W - SMART                NA      
28 7525             Fennings St / Queen St W                        NA      
29 7426             Fleet St / Garrison Rd (Fort York)              NA      
30 7179             Bloor GO / UP Station (West Toronto Railpath)   NA      
31 7179             Bloor GO / UP Station/ Rail Path                NA      
32 7177             East Liberty St / Pirandello St                 NA      
33 7578             Oak St / Parliament St                        7114      
34 7578             Oak St / Parliament St                        7299      
35 7472             Dundas St E / Victoria St                     7333      
36 7472             Dundas St E / Victoria St                     7443      
37 7407             University Ave / Queen St W                     NA      
38 7423             Merton St / Al Green Ln - SMART                 NA      
39 7423             Merton St / Al Green Ln                         NA      
40 7535             Wolsley St / Palmerston Ave - SMART             NA      
41 7134             Marlborough Ave / Yonge St                      NA      
42 7019             Temperance St. Station                          NA      
43 7019             Temperance St / Yonge St                      7713      
44 7413             Dundas St W / Watkinson Ave - SMART             NA      
45 7413             Dundas St W / Watkinson Ave                     NA      
46 7560             Glenwood Ave / Runnymede Rd - SMART             NA      
47 7560             Glenwood Ave / Runnymede Rd                     NA      
48 7330             Lee Ave / Queen St E                          7662      
49 7392             Woodbine Subway Green P SMART                   NA      
50 7482             Danforth Ave / Sibley Ave - SMART               NA      
51 7482             Danforth Ave / Sibley Ave                     7088      

In [15]:
stations_fuzz_address <- stringdist_join(station_id_changed,
                                         stations,
                                         mode = "left",
                                         by = c(Start.Station.Name = "address"),
                                         max_dist = 6)

In [16]:
stations_fuzz_address %>% select(Start.Station.Id,
                                 Start.Station.Name,
                                 station_id,
                                 name.y,
                                 address.y)

Start.Station.Id Start.Station.Name                            station_id
1  7113             Parliament St / Aberdeen Ave                    NA      
2  7282             Adelaide St W / Bay St - SMART                  NA      
3  7013             Scott St / The Esplanade                        NA      
4  7011             Wellington St W / Portland St                 7469      
5  7275             Queen St W / James St                         7542      
6  7491             D'Arcy St / Spadina Ave - SMART                 NA      
7  7382             Simcoe St / Adelaide St W                       NA      
8  7255             Stewart St / Bathurst St  - SMART               NA      
9  7544             Foster Pl / Elizabeth St - SMART                NA      
10 7544             Foster Pl / Elizabeth St                        NA      
11 7017             Widmer St / Adelaide St W                       NA      
12 7017             Widmer St / Adelaide St                         NA      
13 7293             College St / McCaul St                        7007      
14 7293             College St / McCaul St                        7023      
15 7293             College St / McCaul St                        7078      
16 7293             College St / McCaul St                        7199      
17 7293             College St / McCaul St                        7547      
18 7653             Bloor St W / Indian Rd                          NA      
19 7049             Queen St W / Portland St                      7542      
20 7509             Ontario St / King St E                        7373      
21 7167             Queen St E / George St (Moss Park)              NA      
22 7060             Princess St / Adelaide St E                     NA      
23 7060             Princess St / Adelaide St                       NA      
24 7525             Fennings St / Queen St W - SMART                NA      
25 7525             Fennings St / Queen St W                        NA      
26 7426             Fleet St / Garrison Rd (Fort York)              NA      
27 7179             Bloor GO / UP Station (West Toronto Railpath)   NA      
28 7179             Bloor GO / UP Station/ Rail Path                NA      
29 7177             East Liberty St / Pirandello St                 NA      
30 7578             Oak St / Parliament St                        7114      
31 7578             Oak St / Parliament St                        7299      
32 7472             Dundas St E / Victoria St                     7333      
33 7407             University Ave / Queen St W                   7284      
34 7423             Merton St / Al Green Ln - SMART                 NA      
35 7423             Merton St / Al Green Ln                         NA      
36 7535             Wolsley St / Palmerston Ave - SMART             NA      
37 7134             Marlborough Ave / Yonge St                      NA      
38 7019             Temperance St. Station                          NA      
39 7019             Temperance St / Yonge St                        NA      
40 7413             Dundas St W / Watkinson Ave - SMART             NA      
41 7413             Dundas St W / Watkinson Ave                     NA      
42 7560             Glenwood Ave / Runnymede Rd - SMART             NA      
43 7560             Glenwood Ave / Runnymede Rd                     NA      
44 7330             Lee Ave / Queen St E                            NA      
45 7392             Woodbine Subway Green P SMART                   NA      
46 7482             Danforth Ave / Sibley Ave - SMART               NA      
47 7482             Danforth Ave / Sibley Ave                     7088      
48 7482             Danforth Ave / Sibley Ave                     7090      
49 7482             Danforth Ave / Sibley Ave                     7093      
50 7482             Danforth Ave / Sibley Ave                     7734      
51 7621             Long Branch GO Station                          NA      

Unfortunately, none of the fuzzy matches on either the station name or address fields look of the station information data look particularly promising. Generally the match identifies one of the streets correctly but matches to an intersection with a different cross street. This implies that the station locations of the unmatched IDs are not in the station information dataset and a new strategy is needed.

### Identify locations for stations that do not appear in station information

Most, though not all, stations are at street intersections. The City of Toronto provides a file of the locations of all intersections in the city in the Open Data Portal, which should be helpful for locating those stations which do occur at intersections. This data has already been loaded above. The first step is to try an inner join to look for direct matches between station locations and intersection names.

In [17]:
stations_intersection <- inner_join(station_id_changed,
                                    intersections,
                                    by = join_by(Start.Station.Name == INTERSECTION_DESC))

In [18]:
stations_intersection

Start.Station.Id Start.Station.Name          name address output _id  
1 7275             Queen St W / James St       NA   NA      NA     43259
2 7544             Foster Pl / Elizabeth St    NA   NA      NA     40195
3 7653             Bloor St W / Indian Rd      NA   NA      NA      3501
4 7653             Bloor St W / Indian Rd      NA   NA      NA     38036
5 7049             Queen St W / Portland St    NA   NA      NA     42303
6 7578             Oak St / Parliament St      NA   NA      NA     22859
7 7472             Dundas St E / Victoria St   NA   NA      NA      9996
8 7407             University Ave / Queen St W NA   NA      NA     22551
9 7482             Danforth Ave / Sibley Ave   NA   NA      NA      9663
  INTERSECTION_ID DATE_EFFECTIVE      DATE_EXPIRY         ELEVATION_ID ⋯
1 13466379        2024-04-12 15:42:23 3000-01-01 05:00:00  7152        ⋯
2 13466018        2023-08-17 12:53:58 3000-01-01 05:00:00  4542        ⋯
3 13466046        2008-12-12 04:22:46 3000-01-01 05:00:00 12465        ⋯
4 13466037        2022-03-28 12:58:19 3000-01-01 05:00:00 14404        ⋯
5 13467150        2024-01-31 12:56:38 3000-01-01 05:00:00  4235        ⋯
6 20235156        2008-12-12 04:22:46 3000-01-01 05:00:00 14181        ⋯
7 13465716        2008-12-12 04:22:46 3000-01-01 05:00:00 11374        ⋯
8 13466604        2008-12-12 04:22:46 3000-01-01 05:00:00  9968        ⋯
9 13459659        2008-12-12 04:22:46 3000-01-01 05:00:00  1800        ⋯
  ELEVATION_LEVEL ELEVATION ELEVATION_UNIT HEIGHT_RESTRICTION
1 NA              NA        None           NA                
2 NA              NA        None           NA                
3 NA              NA        None           NA                
4 NA              NA        None           NA                
5 NA              NA        None           NA                
6 NA              NA        None           NA                
7 NA              NA        None           NA                
8 NA              NA        None           NA                
9 NA              NA        None           NA                
  HEIGHT_RESTRICTION_UNIT STATE TRANS_ID_CREATE TRANS_ID_EXPIRE OBJECTID
1 None                    8     370649          -1              114450  
2 None                    8     363175          -1              110618  
3 None                    8     200000          -1                5567  
4 None                    8     344050          -1              106326  
5 None                    8     368160          -1              113245  
6 None                    8     200000          -1               40384  
7 None                    8     200000          -1               18404  
8 None                    8     200000          -1               39861  
9 None                    8     200000          -1               17645  
  geometry                                                                      
1 {'type': 'MultiPoint', 'coordinates': [[-79.3807162626028, 43.6521008898127]]}
2 {'type': 'MultiPoint', 'coordinates': [[-79.3848220785899, 43.6545534061131]]}
3 {'type': 'MultiPoint', 'coordinates': [[-79.4570501089068, 43.6553527151862]]}
4 {'type': 'MultiPoint', 'coordinates': [[-79.4568442039919, 43.6553957541211]]}
5 {'type': 'MultiPoint', 'coordinates': [[-79.4014174537963, 43.6477126767303]]}
6 {'type': 'MultiPoint', 'coordinates': [[-79.3665329339236, 43.6607189905741]]}
7 {'type': 'MultiPoint', 'coordinates': [[-79.3795762008715, 43.6562913281717]]}
8 {'type': 'MultiPoint', 'coordinates': [[-79.386628635294, 43.6508528459786]]} 
9 {'type': 'MultiPoint', 'coordinates': [[-79.2926856191101, 43.690223652078]]}

This identifies 8 stations (the same maps to two intersections because a street is discontinuous across each side of an intersection), which is not particularly successful.

The next approach is to try fuzzy matching the station names to the intersection names.

In [19]:
stations_fuzz_intersection <- stringdist_left_join(station_id_changed,
                                                   intersections,
                                                   by = c(Start.Station.Name = "INTERSECTION_DESC"),
                                                   max_dist = 2)

In [20]:
stations_fuzz_intersection %>% select(Start.Station.Id,
                                      Start.Station.Name,
                                      INTERSECTION_DESC)

Start.Station.Id Start.Station.Name                           
1  7113             Parliament St / Aberdeen Ave                 
2  7282             Adelaide St W / Bay St - SMART               
3  7013             Scott St / The Esplanade                     
4  7011             Wellington St W / Portland St                
5  7275             Queen St W / James St                        
6  7491             D'Arcy St / Spadina Ave - SMART              
7  7382             Simcoe St / Adelaide St W                    
8  7255             Stewart St / Bathurst St  - SMART            
9  7544             Foster Pl / Elizabeth St - SMART             
10 7544             Foster Pl / Elizabeth St                     
11 7017             Widmer St / Adelaide St W                    
12 7017             Widmer St / Adelaide St                      
13 7293             College St / McCaul St                       
14 7653             Bloor St W / Indian Rd                       
15 7653             Bloor St W / Indian Rd                       
16 7049             Queen St W / Portland St                     
17 7509             Ontario St / King St E                       
18 7167             Queen St E / George St (Moss Park)           
19 7060             Princess St / Adelaide St E                  
20 7060             Princess St / Adelaide St                    
21 7525             Fennings St / Queen St W - SMART             
22 7525             Fennings St / Queen St W                     
23 7426             Fleet St / Garrison Rd (Fort York)           
24 7179             Bloor GO / UP Station (West Toronto Railpath)
25 7179             Bloor GO / UP Station/ Rail Path             
26 7177             East Liberty St / Pirandello St              
27 7578             Oak St / Parliament St                       
28 7472             Dundas St E / Victoria St                    
29 7407             University Ave / Queen St W                  
30 7423             Merton St / Al Green Ln - SMART              
31 7423             Merton St / Al Green Ln                      
32 7535             Wolsley St / Palmerston Ave - SMART          
33 7134             Marlborough Ave / Yonge St                   
34 7019             Temperance St. Station                       
35 7019             Temperance St / Yonge St                     
36 7413             Dundas St W / Watkinson Ave - SMART          
37 7413             Dundas St W / Watkinson Ave                  
38 7560             Glenwood Ave / Runnymede Rd - SMART          
39 7560             Glenwood Ave / Runnymede Rd                  
40 7330             Lee Ave / Queen St E                         
41 7392             Woodbine Subway Green P SMART                
42 7482             Danforth Ave / Sibley Ave - SMART            
43 7482             Danforth Ave / Sibley Ave                    
44 7621             Long Branch GO Station                       
45 7638             Warehouse EBS-Station                        
   INTERSECTION_DESC          
1  NA                         
2  NA                         
3  NA                         
4  NA                         
5  Queen St W / James St      
6  NA                         
7  NA                         
8  NA                         
9  NA                         
10 Foster Pl / Elizabeth St   
11 NA                         
12 NA                         
13 College St / Mc Caul St    
14 Bloor St W / Indian Rd     
15 Bloor St W / Indian Rd     
16 Queen St W / Portland St   
17 NA                         
18 NA                         
19 NA                         
20 NA                         
21 NA                         
22 NA                         
23 NA                         
24 NA                         
25 NA                         
26 NA                         
27 Oak St / Parliament St     
28 Dundas St E / Victoria St  
29 University Ave / Queen St W
30 NA                         
31 NA 

Fuzzy matching returns almost identical matches to the simple inner join. This is initially surprising, because a file containing all intersections should match most of the stations in the ride data that we need locations for (a few are not at intersections).

Exploring the intersection data, it becomes clear that a major issue with the matching (fuzzy or otherwise) between the ride data and intersection data is that the order of how cross-streets are listed is not standardized. The same two streets intersecting, but listed in a different order, will not match directly and will not fuzzy match well using a simple fuzzy matcher.

What is needed is a tokenized fuzzy matching approach, where the addresses are broken up into tokens (words) and then matched as sets of tokens rather than as coherent strings. The collection of tokens for a given intersection should be the same regardless of the order that the cross streets are listed in. In Python, this can be done with the popular fuzzywuzzy package. In R, there are multiple ports but the one built natively in r is levitate. Unlike fuzzyjoin, levitate is built for string matching but not expressly for joining.

In [36]:
stations_levitate_intersection <- NULL
for (i in 1:length(station_id_changed$Start.Station.Name)) {
    temp_matches <- c()
    for (j in 1:length(intersections$INTERSECTION_DESC)) {
        temp_matches[j] = lev_token_set_ratio(station_id_changed$Start.Station.Name[i],
                                              intersections$INTERSECTION_DESC[j])
        }
    temp_row <- tibble_row(Start.Station.Id = station_id_changed$Start.Station.Id[i],
                           Start.Station.Name = station_id_changed$Start.Station.Name[i],
                           INTERSECTION_DESC = intersections$INTERSECTION_DESC[which.max(temp_matches)],
                           INTERSECTION_ID = intersections$INTERSECTION_ID[which.max(temp_matches)],
                           geometry = intersections$geometry[which.max(temp_matches)],
                           Score = max(temp_matches))
    stations_levitate_intersection <- bind_rows(stations_levitate_intersection, temp_row)
}

In [37]:
stations_levitate_intersection

Start.Station.Id Start.Station.Name                           
1  7113             Parliament St / Aberdeen Ave                 
2  7282             Adelaide St W / Bay St - SMART               
3  7013             Scott St / The Esplanade                     
4  7011             Wellington St W / Portland St                
5  7275             Queen St W / James St                        
6  7491             D'Arcy St / Spadina Ave - SMART              
7  7382             Simcoe St / Adelaide St W                    
8  7255             Stewart St / Bathurst St  - SMART            
9  7544             Foster Pl / Elizabeth St - SMART             
10 7544             Foster Pl / Elizabeth St                     
11 7017             Widmer St / Adelaide St W                    
12 7017             Widmer St / Adelaide St                      
13 7293             College St / McCaul St                       
14 7653             Bloor St W / Indian Rd                       
15 7049             Queen St W / Portland St                     
16 7509             Ontario St / King St E                       
17 7167             Queen St E / George St (Moss Park)           
18 7060             Princess St / Adelaide St E                  
19 7060             Princess St / Adelaide St                    
20 7525             Fennings St / Queen St W - SMART             
21 7525             Fennings St / Queen St W                     
22 7426             Fleet St / Garrison Rd (Fort York)           
23 7179             Bloor GO / UP Station (West Toronto Railpath)
24 7179             Bloor GO / UP Station/ Rail Path             
25 7177             East Liberty St / Pirandello St              
26 7578             Oak St / Parliament St                       
27 7472             Dundas St E / Victoria St                    
28 7407             University Ave / Queen St W                  
29 7423             Merton St / Al Green Ln - SMART              
30 7423             Merton St / Al Green Ln                      
31 7535             Wolsley St / Palmerston Ave - SMART          
32 7134             Marlborough Ave / Yonge St                   
33 7019             Temperance St. Station                       
34 7019             Temperance St / Yonge St                     
35 7413             Dundas St W / Watkinson Ave - SMART          
36 7413             Dundas St W / Watkinson Ave                  
37 7560             Glenwood Ave / Runnymede Rd - SMART          
38 7560             Glenwood Ave / Runnymede Rd                  
39 7330             Lee Ave / Queen St E                         
40 7392             Woodbine Subway Green P SMART                
41 7482             Danforth Ave / Sibley Ave - SMART            
42 7482             Danforth Ave / Sibley Ave                    
43 7621             Long Branch GO Station                       
44 7638             Warehouse EBS-Station                        
   INTERSECTION_DESC                               INTERSECTION_ID
1  Aberdeen Ave / Parliament St                    13464279       
2  Bay St / Adelaide St W                          13466743       
3  The Esplanade / Scott St                        13467327       
4  Portland St / Wellington St W                   30114865       
5  Queen St W / James St                           13466379       
6  Spadina Ave / D'Arcy St / Glen Baillie Pl       13466135       
7  Adelaide St W / Simcoe St                       13466978       
8  Bathurst St / Stewart St                        13467820       
9  Foster Pl                                       13465978       
10 Foster Pl                                       13465978       
11 Adelaide St W / Widmer St                       13467149       
12 Adelaide St W / Widmer St                       13467149       
13 College St                                      14017913       
14 Bloor St W / Indian Rd                          13466046       
15 Queen St W / Ww E Portlan

In [38]:
saveRDS(stations_levitate_intersection, "./Data/stations_levitate_intersection.RDS")

Other than being quite computationally inefficient (~1 minute per station) , this nested for loop approach using token set matching in levitate provides much better matching between the ride data stations and the intersection data than the simple fuzzy match in fuzzyjoin. There may well be a way to vectorize the process, at least for checking a given station in the ride data against all intersections (in place of the inner for loop). For larger comparisons, the zoomerjoin package might well be worth considering as an alternative, though it is not quite as straightforward to install (compiled using Rust) and would be challenging to install in the conda environment used for this project. I already had to build levitate as a conda package to use here.

Manual inspection shows fairly high overall match quality excepting situations where the station in the ride data is not at an intersection. Generally, matches with a score above 0.8 are correct. In a few cases, where there is an 'intersection' that contains only 1 street in the name in the file, that is chosen as a better match. Interestingly, in most of these cases, the fuzzyjoin matching performed better. An ensemble of these approaches, where stations not matched correctly by fuzzyjoin are passed to levitate, seems to be the best option.

In [21]:
stations_fuzzjoin_found <- stations_fuzz_intersection %>% filter(!is.na(INTERSECTION_DESC))

In [22]:
stations_fuzzjoin_found

Start.Station.Id Start.Station.Name          name address output _id  
1  7275             Queen St W / James St       NA   NA      NA     43259
2  7544             Foster Pl / Elizabeth St    NA   NA      NA     40195
3  7293             College St / McCaul St      NA   NA      NA     18163
4  7653             Bloor St W / Indian Rd      NA   NA      NA      3501
5  7653             Bloor St W / Indian Rd      NA   NA      NA     38036
6  7049             Queen St W / Portland St    NA   NA      NA     42303
7  7578             Oak St / Parliament St      NA   NA      NA     22859
8  7472             Dundas St E / Victoria St   NA   NA      NA      9996
9  7407             University Ave / Queen St W NA   NA      NA     22551
10 7482             Danforth Ave / Sibley Ave   NA   NA      NA      9663
   INTERSECTION_ID DATE_EFFECTIVE      DATE_EXPIRY         ELEVATION_ID ⋯
1  13466379        2024-04-12 15:42:23 3000-01-01 05:00:00  7152        ⋯
2  13466018        2023-08-17 12:53:58 3000-01-01 05:00:00  4542        ⋯
3  13465273        2008-12-12 04:22:46 3000-01-01 05:00:00 29937        ⋯
4  13466046        2008-12-12 04:22:46 3000-01-01 05:00:00 12465        ⋯
5  13466037        2022-03-28 12:58:19 3000-01-01 05:00:00 14404        ⋯
6  13467150        2024-01-31 12:56:38 3000-01-01 05:00:00  4235        ⋯
7  20235156        2008-12-12 04:22:46 3000-01-01 05:00:00 14181        ⋯
8  13465716        2008-12-12 04:22:46 3000-01-01 05:00:00 11374        ⋯
9  13466604        2008-12-12 04:22:46 3000-01-01 05:00:00  9968        ⋯
10 13459659        2008-12-12 04:22:46 3000-01-01 05:00:00  1800        ⋯
   ELEVATION_LEVEL ELEVATION ELEVATION_UNIT HEIGHT_RESTRICTION
1  NA              NA        None           NA                
2  NA              NA        None           NA                
3  NA              NA        None           NA                
4  NA              NA        None           NA                
5  NA              NA        None           NA                
6  NA              NA        None           NA                
7  NA              NA        None           NA                
8  NA              NA        None           NA                
9  NA              NA        None           NA                
10 NA              NA        None           NA                
   HEIGHT_RESTRICTION_UNIT STATE TRANS_ID_CREATE TRANS_ID_EXPIRE OBJECTID
1  None                    8     370649          -1              114450  
2  None                    8     363175          -1              110618  
3  None                    8     200000          -1               32168  
4  None                    8     200000          -1                5567  
5  None                    8     344050          -1              106326  
6  None                    8     368160          -1              113245  
7  None                    8     200000          -1               40384  
8  None                    8     200000          -1               18404  
9  None                    8     200000          -1               39861  
10 None                    8     200000          -1               17645  
   geometry                                                                      
1  {'type': 'MultiPoint', 'coordinates': [[-79.3807162626028, 43.6521008898127]]}
2  {'type': 'MultiPoint', 'coordinates': [[-79.3848220785899, 43.6545534061131]]}
3  {'type': 'MultiPoint', 'coordinates': [[-79.3934845254722, 43.6591999315297]]}
4  {'type': 'MultiPoint', 'coordinates': [[-79.4570501089068, 43.6553527151862]]}
5  {'type': 'MultiPoint', 'coordinates': [[-79.4568442039919, 43.6553957541211]]}
6  {'type': 'MultiPoint', 'coordinates': [[-79.4014174537963, 43.6477126767303]]}
7  {'type': 'MultiPoint', 'coordinates': [[-79.3665329339236, 43.6607189905741]]}
8  {'type': 'MultiPoint', 'coordinates': [[-79.3795762008715, 43.6562913281717]]}
9  {'type': 'MultiPoint', 'coordinates': [[-79.386628635294, 43.6508528459786]]} 
10 {'type': 'MultiPoint', 'coordinates': [[-79.2

There is one duplicate entry in the successful list of found stations, as it maps to both parts of a discontinuous intersection. This can be dropped to create a single location (they are only metres apart).

In [26]:
stations_fuzzjoin_found <- stations_fuzzjoin_found %>% filter(!row_number() == 5)

In [25]:
stations_fuzzjoin_failed <- stations_fuzz_intersection %>% filter(is.na(INTERSECTION_DESC))

In [57]:
stations_levitate_intersection_2 <- NULL
for (i in 1:length(stations_fuzzjoin_failed$Start.Station.Name)) {
    temp_matches <- c()
    for (j in 1:length(intersections$INTERSECTION_DESC)) {
        temp_matches[j] = lev_token_set_ratio(stations_fuzzjoin_failed$Start.Station.Name[i],
                                              intersections$INTERSECTION_DESC[j])
        }
    temp_row <- tibble_row(Start.Station.Id = stations_fuzzjoin_failed$Start.Station.Id[i],
                           Start.Station.Name = stations_fuzzjoin_failed$Start.Station.Name[i],
                           INTERSECTION_DESC = intersections$INTERSECTION_DESC[which.max(temp_matches)],
                           INTERSECTION_ID = intersections$INTERSECTION_ID[which.max(temp_matches)],
                           geometry = intersections$geometry[which.max(temp_matches)],
                           Score = max(temp_matches))
    stations_levitate_intersection_2 <- bind_rows(stations_levitate_intersection, temp_row)
}

In [58]:
stations_levitate_intersection_2

Start.Station.Id Start.Station.Name                           
1  7113             Parliament St / Aberdeen Ave                 
2  7282             Adelaide St W / Bay St - SMART               
3  7013             Scott St / The Esplanade                     
4  7011             Wellington St W / Portland St                
5  7491             D'Arcy St / Spadina Ave - SMART              
6  7382             Simcoe St / Adelaide St W                    
7  7255             Stewart St / Bathurst St  - SMART            
8  7544             Foster Pl / Elizabeth St - SMART             
9  7017             Widmer St / Adelaide St W                    
10 7017             Widmer St / Adelaide St                      
11 7509             Ontario St / King St E                       
12 7167             Queen St E / George St (Moss Park)           
13 7060             Princess St / Adelaide St E                  
14 7060             Princess St / Adelaide St                    
15 7525             Fennings St / Queen St W - SMART             
16 7525             Fennings St / Queen St W                     
17 7426             Fleet St / Garrison Rd (Fort York)           
18 7179             Bloor GO / UP Station (West Toronto Railpath)
19 7179             Bloor GO / UP Station/ Rail Path             
20 7177             East Liberty St / Pirandello St              
21 7423             Merton St / Al Green Ln - SMART              
22 7423             Merton St / Al Green Ln                      
23 7535             Wolsley St / Palmerston Ave - SMART          
24 7134             Marlborough Ave / Yonge St                   
25 7019             Temperance St. Station                       
26 7019             Temperance St / Yonge St                     
27 7413             Dundas St W / Watkinson Ave - SMART          
28 7413             Dundas St W / Watkinson Ave                  
29 7560             Glenwood Ave / Runnymede Rd - SMART          
30 7560             Glenwood Ave / Runnymede Rd                  
31 7330             Lee Ave / Queen St E                         
32 7392             Woodbine Subway Green P SMART                
33 7482             Danforth Ave / Sibley Ave - SMART            
34 7621             Long Branch GO Station                       
35 7638             Warehouse EBS-Station                        
   INTERSECTION_DESC                               INTERSECTION_ID
1  Aberdeen Ave / Parliament St                    13464279       
2  Bay St / Adelaide St W                          13466743       
3  The Esplanade / Scott St                        13467327       
4  Portland St / Wellington St W                   30114865       
5  Spadina Ave / D'Arcy St / Glen Baillie Pl       13466135       
6  Adelaide St W / Simcoe St                       13466978       
7  Bathurst St / Stewart St                        13467820       
8  Foster Pl                                       13465978       
9  Adelaide St W / Widmer St                       13467149       
10 Adelaide St W / Widmer St                       13467149       
11 King St E / Ontario St                          13466404       
12 Queen St E / George St / Moss Park Trl          13466082       
13 Adelaide St E / Princess St                     13466300       
14 Adelaide St E / Princess St                     13466300       
15 Queen St W                                      13467800       
16 Queen St W / Fennings St / White Squirrel Way   13467776       
17 York Rd                                         13458960       
18 Station St                                      14051381       
19 Station St                                      14051381       
20 Pirandello St / East Liberty St                 14254033       
21 Merton St / Al Green Lane / Ln E Yonge S Merton 14036433       
22 Merton St / Al Green Lane / Ln E Yonge S Merton 14036433       
23 Palmerston Ave / Palmerston Sq                  13464151       
24 Yonge St / Marlb

In [59]:
saveRDS(stations_levitate_intersection_2, "./Data/stations_levitate_intersection_2.RDS")

In [26]:
stations_levitate_intersection <- readRDS("./Data/stations_levitate_intersection.rds")

In [27]:
stations_levitate_intersection_2 <- readRDS("./Data/stations_levitate_intersection_2.RDS")

NOTE: This is a temporary test of using levitate's inbuilt lev_score_multiple() function to replace the inner for loop. It may be slightly faster based on a test of a single station, but the code is cleaner in some respects and dirtier in others. I have not run it yet...

In [ ]:
stations_levitate_intersection_3 = NULL
for (i in 1:length(stations_fuzzjoin_failed$Start.Station.Name)) {
    temp_matches <- lev_score_multiple(stations_fuzzjoin_failed$Start.Station.Name[i],
                                          intersections$INTERSECTION_DESC,
                                          .fn = lev_token_set_ratio)
    temp_row <- tibble_row(Start.Station.Id = stations_fuzzjoin_failed$Start.Station.Id[i],
                           Start.Station.Name = stations_fuzzjoin_failed$Start.Station.Name[i],
                           INTERSECTION_DESC = names(temp_matches[1]),
                           INTERSECTION_ID = intersections$INTERSECTION_ID[intersections$INTERSECTION_DESC == names(temp_matches[1])],
                           geometry = intersections$geometry[intersections$INTERSECTION_DESC == names(temp_matches[1])],
                           Score = temp_matches[[1]])
    stations_levitate_intersection_3 <- bind_rows(stations_levitate_intersection, temp_row)
}

Some stations in the levitate-based fuzzy match with the intersection data have duplicate entries for the same ID (often for 'regular' and SMART stations) and have already been matched correctly in one form using fuzzyjoin. These can be dropped before considering the remaining matches. NOTE this dropping could be done before the levitate search to reduce overall computation time.

In [28]:
stations_levitate_filtered <- stations_levitate_intersection_2 %>%
filter(!(Start.Station.Id %in% stations_fuzzjoin_found$Start.Station.Id))

At this point, the assignment of correct or incorrect matches must be done manually as there is no clear cutoff in match score. In two cases, score<0.8 is associated with a correct match. The best approach is to split into tables for correct and incorrect matches, and then the latter can be manually edited or discarded depending on time cost.

In [29]:
incorrect_match_indices <- c(14, 16:18, 22, 24, 26, 27, 31:33)
stations_levitate_correct <- stations_levitate_filtered %>%
filter(!row_number() %in% incorrect_match_indices)
stations_levitate_incorrect <- stations_levitate_filtered %>%
filter(row_number() %in% incorrect_match_indices)

In [30]:
stations_levitate_correct

Start.Station.Id Start.Station.Name                 
1  7113             Parliament St / Aberdeen Ave       
2  7282             Adelaide St W / Bay St - SMART     
3  7013             Scott St / The Esplanade           
4  7011             Wellington St W / Portland St      
5  7491             D'Arcy St / Spadina Ave - SMART    
6  7382             Simcoe St / Adelaide St W          
7  7255             Stewart St / Bathurst St  - SMART  
8  7017             Widmer St / Adelaide St W          
9  7017             Widmer St / Adelaide St            
10 7509             Ontario St / King St E             
11 7167             Queen St E / George St (Moss Park) 
12 7060             Princess St / Adelaide St E        
13 7060             Princess St / Adelaide St          
14 7525             Fennings St / Queen St W           
15 7177             East Liberty St / Pirandello St    
16 7423             Merton St / Al Green Ln - SMART    
17 7423             Merton St / Al Green Ln            
18 7134             Marlborough Ave / Yonge St         
19 7019             Temperance St / Yonge St           
20 7560             Glenwood Ave / Runnymede Rd - SMART
21 7560             Glenwood Ave / Runnymede Rd        
22 7330             Lee Ave / Queen St E               
   INTERSECTION_DESC                               INTERSECTION_ID
1  Aberdeen Ave / Parliament St                    13464279       
2  Bay St / Adelaide St W                          13466743       
3  The Esplanade / Scott St                        13467327       
4  Portland St / Wellington St W                   30114865       
5  Spadina Ave / D'Arcy St / Glen Baillie Pl       13466135       
6  Adelaide St W / Simcoe St                       13466978       
7  Bathurst St / Stewart St                        13467820       
8  Adelaide St W / Widmer St                       13467149       
9  Adelaide St W / Widmer St                       13467149       
10 King St E / Ontario St                          13466404       
11 Queen St E / George St / Moss Park Trl          13466082       
12 Adelaide St E / Princess St                     13466300       
13 Adelaide St E / Princess St                     13466300       
14 Queen St W / Fennings St / White Squirrel Way   13467776       
15 Pirandello St / East Liberty St                 14254033       
16 Merton St / Al Green Lane / Ln E Yonge S Merton 14036433       
17 Merton St / Al Green Lane / Ln E Yonge S Merton 14036433       
18 Yonge St / Marlborough Ave / Price St           13461783       
19 Yonge St / Temperance St                        13466551       
20 Runnymede Rd / Glenwood Ave                     13465858       
21 Runnymede Rd / Glenwood Ave                     13465858       
22 Queen St E / Lee Ave                            13463187       
   geometry                                                                      
1  {'type': 'MultiPoint', 'coordinates': [[-79.3682787943632, 43.6650446564633]]}
2  {'type': 'MultiPoint', 'coordinates': [[-79.3808101970891, 43.6498927202986]]}
3  {'type': 'MultiPoint', 'coordinates': [[-79.3752644227303, 43.6463225154789]]}
4  {'type': 'MultiPoint', 'coordinates': [[-79.3994793772098, 43.6430140298378]]}
5  {'type': 'MultiPoint', 'coordinates': [[-79.398427359226, 43.6539024276164]]} 
6  {'type': 'MultiPoint', 'coordinates': [[-79.3866213342558, 43.6486382517816]]}
7  {'type': 'MultiPoint', 'coordinates': [[-79.4023967156926, 43.6431940739398]]}
8  {'type': 'MultiPoint', 'coordinates': [[-79.3915645414971, 43.6475822548383]]}
9  {'type': 'MultiPoint', 'coordinates': [[-79.3915645414971, 43.6475822548383]]}
10 {'type': 'MultiPoint', 'coordinates': [[-79.366059144905, 43.6517548282251]]} 
11 {'type': 'MultiPoint', 'coordinates': [[-79.3720473032044, 43.6539653546431]]}
12 {'type': 'MultiPoint', 'coordinates': [[-79.3673883989911, 43.6524122618697]]}
13 {'type': 'MultiPoint', 'coordinates': [[-79.3673883989911, 43.6524122618697]]}
14 {'type': 'MultiPoint', 

At this stage, there are a few duplicated entries with the same ID, often where one is a SMART station and one is not. In all cases, these both map to the same location so one entry can safely be dropped to avoid duplicated stations.

In [32]:
stations_levitate_correct <- stations_levitate_correct %>% filter(!row_number() %in% c(9, 13, 16, 20))

In [34]:
saveRDS(stations_fuzzjoin_found, "./Data/stations_fuzzjoin_found.rds")
saveRDS(stations_levitate_correct, "./Data/stations_levitate_correct.rds")
saveRDS(stations_levitate_incorrect, "./Data/stations_levitate_incorrect.rds")

At this point, the various station information tables can be merged for further geospatial mapping. This will be performed in a new script (using a conda environment built for geospatial analysis instead of fuzzy joining).